In [1]:
import numpy as np

In [25]:
a = np.zeros(10)  
print(a, "\n")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 



In [30]:
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [31]:
b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [67]:
c = np.arange(0, 9).reshape((3, 3))
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [33]:
d = np.nonzero([1,2,0,0,4,0])
d

(array([0, 1, 4]),)

In [34]:
e = np.eye(3,3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
f = np.random.random((3,3,3))
f

array([[[0.29499505, 0.60961846, 0.01446074],
        [0.26997806, 0.98258369, 0.42597072],
        [0.80824066, 0.558996  , 0.30810987]],

       [[0.67423577, 0.16732838, 0.18378128],
        [0.86726855, 0.04186896, 0.77676309],
        [0.84170478, 0.90478331, 0.49251225]],

       [[0.88003938, 0.51227009, 0.36280877],
        [0.75965738, 0.69316401, 0.21140154],
        [0.6747748 , 0.52323804, 0.44347275]]])

In [49]:
np.random.seed(1000)
g = np.random.random((10,10))
g

min = np.amin(g)
print(min)

max = np.amax(g)
print(max)

0.010421700558954194
0.9820274845981977


In [63]:
np.random.seed(42)
z = np.random.random((10,3))
print(z)
print(np.mean(z))


[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]
 [0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378]
 [0.51423444 0.59241457 0.04645041]]
0.43859727209743676


In [77]:
x = np.diag([1, 2, 3, 4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [80]:
x= np.random.random((5,5))
print(x)
print((x - np.mean(x))/np.std(x))


[[0.86310343 0.62329813 0.33089802 0.06355835 0.31098232]
 [0.32518332 0.72960618 0.63755747 0.88721274 0.47221493]
 [0.11959425 0.71324479 0.76078505 0.5612772  0.77096718]
 [0.4937956  0.52273283 0.42754102 0.02541913 0.10789143]
 [0.03142919 0.63641041 0.31435598 0.50857069 0.90756647]]
[[ 1.40271656  0.51116394 -0.57592662 -1.56984705 -0.64996959]
 [-0.59717285  0.906398    0.5641776   1.49235063 -0.05053601]
 [-1.36151575  0.84556932  1.02231539  0.28058137  1.06017071]
 [ 0.02969702  0.1372804  -0.21662549 -1.71164177 -1.40502471]
 [-1.68929746  0.55991304 -0.63742694  0.08462814  1.56802211]]


In [82]:
a = [1,2,3]
b = [4,1,6]
np.intersect1d(a,b)


array([1])

In [101]:
g = np.random.random(10)
print(g)
g.sort()
print(g)

[0.43249917 0.0181432  0.69143786 0.46969065 0.12822219 0.89133705
 0.91820362 0.07312099 0.04544794 0.4385729 ]
[0.0181432  0.04544794 0.07312099 0.12822219 0.43249917 0.4385729
 0.46969065 0.69143786 0.89133705 0.91820362]


In [110]:
np.random.seed(42)
x = np.random.random(10)
print(x)
x[x.argmax()] = 0
print(x)



[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]
[0.37454012 0.         0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]


In [114]:
x = np.random.rand(3, 4)
print(x)
b = x - x.mean(axis=1, keepdims=True)
print(b)

[[0.29214465 0.36636184 0.45606998 0.78517596]
 [0.19967378 0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159 0.94888554]]
[[-0.18279346 -0.10857627 -0.01886813  0.31023785]
 [-0.13851952  0.17604114  0.25422127 -0.29174289]
 [ 0.15954333 -0.2774774  -0.38294993  0.50088401]]


In [117]:
Z = np.arange(10000) 
np.random.shuffle(Z) 
n = 5
print(Z)
sorted_index_array = np.argsort(Z)
sorted_array = Z[sorted_index_array]
rslt = sorted_array[-n : ]
print(rslt[0])

[5109  562 4592 ... 9108 1466 1543]
9995


In [123]:
x = np.random.randint(0, 10, (5, 3))
print(x)
f = np.where(x < 4, x, x**2)
print(f)

[[1 2 6]
 [1 4 8]
 [9 7 7]
 [1 0 8]
 [9 3 8]]
[[ 1  2 36]
 [ 1 16 64]
 [81 49 49]
 [ 1  0 64]
 [81  3 64]]
